# Generated by Django 2.1.5 on 2020-03-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mammoth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_score', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='pattern',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='picture',
            field=models.ImageField(upload_to='pattern_images'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='title',
            field=models.CharField(default='pattern_name', max_length=128),
        ),
    ]
