# Generated by Django 2.1.5 on 2020-03-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mammoth', '0002_auto_20200307_1426'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
