# Generated by Django 2.1.5 on 2020-02-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mammoth', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
