# Generated by Django 2.1.5 on 2020-02-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mammoth', '0006_remove_userprofile_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('picture', models.ImageField(blank=True, upload_to='pattern_images')),
            ],
        ),
    ]
