# Generated by Django 2.1.5 on 2020-02-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mammoth', '0008_pattern_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
