# Generated by Django 2.1.5 on 2020-02-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mammoth', '0009_auto_20200225_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='slug',
        ),
    ]
