# Generated by Django 2.1.5 on 2020-02-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mammoth', '0010_remove_pattern_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='picture',
            field=models.ImageField(upload_to='pattern_images'),
        ),
    ]
