# Generated by Django 2.1.5 on 2020-03-07 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mammoth', '0012_auto_20200307_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
