# Generated by Django 2.1.5 on 2020-03-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mammoth', '0013_remove_pattern_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='title',
            field=models.CharField(default='pattern_name', max_length=128),
        ),
    ]
